-- MySQL Script generated by MySQL Workbench
-- Fri Aug 30 10:39:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MedGen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MedGen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MedGen` DEFAULT CHARACTER SET utf8 ;
USE `MedGen` ;

-- -----------------------------------------------------
-- Table `MedGen`.`MedGen_entryId`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MedGen`.`MedGen_entryId` (
  `DB` VARCHAR(45) NOT NULL COMMENT 'Name of the ontology database',
  `id` VARCHAR(45) NOT NULL COMMENT 'Disease ontology identifier',
  `def` VARCHAR(250) NOT NULL,
  `level` INT NULL,
  PRIMARY KEY (`DB`, `id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MedGen`.`MedGen_crossId`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MedGen`.`MedGen_crossId` (
  `DB1` VARCHAR(45) NOT NULL COMMENT 'Name of the database of \"id1\"',
  `id1` VARCHAR(45) NOT NULL COMMENT 'Disease ontology identifier from MedGen',
  `DB2` VARCHAR(45) NOT NULL COMMENT 'Name of the database of \'id2\' ',
  `id2` VARCHAR(45) NOT NULL COMMENT 'Crossreference disease ontology identifier in MedGen',
  PRIMARY KEY (`DB1`, `id1`),
  CONSTRAINT `fk_MedGen_crossId_MedGen_entryId`
    FOREIGN KEY (`DB1` , `id1`)
    REFERENCES `MedGen`.`MedGen_entryId` (`DB` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MedGen`.`MedGen_idNames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MedGen`.`MedGen_idNames` (
  `DB` VARCHAR(45) NOT NULL COMMENT 'Name original database/ontology',
  `id` VARCHAR(45) NOT NULL COMMENT 'Disease ontology identifier from MedGen',
  `syn` VARCHAR(45) NOT NULL COMMENT 'Name or label to to describe the disease identifier',
  `canonical` VARCHAR(45) NOT NULL COMMENT 'TRUE/FALSE if the \"name\" was used as the label for this disease in MedGen',
  PRIMARY KEY (`DB`, `id`),
  INDEX `fk_MedGen_idNames_MedGen_entryId1_idx` (`DB` ASC, `id` ASC) VISIBLE,
  CONSTRAINT `fk_MedGen_idNames_MedGen_entryId1`
    FOREIGN KEY (`DB` , `id`)
    REFERENCES `MedGen`.`MedGen_entryId` (`DB` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MedGen`.`MedGen_sourceFiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MedGen`.`MedGen_sourceFiles` (
  `url` VARCHAR(45) NOT NULL COMMENT 'URL location of the source files',
  `current` VARCHAR(45) NOT NULL COMMENT 'Date of the current version of the source files',
  PRIMARY KEY (`url`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
